name: Deploy to AWS
on:
  push:
    branches: [main]  # Só dispara após merge na main

jobs:
  deploy:
    needs: test  # Só executa se o job de testes (CI) passar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn package  # Gera o .jar

      - name: Deploy to AWS Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: minha-api
          environment_name: minha-api-prod
          version_label: "v1.0.${{ github.run_number }}"
          region: us-east-1
          deployment_package: target/*.jar