name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17' 
          distributon: 'temurin'
      
      - name: Compile Java files
        run: javac -d out/Test $(find -name "*.java")

      - name: Run manual test
        run: java test